# Generated by Django 2.1.7 on 2019-02-21 19:34

import beers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=200)),
                ('harmonization', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('alcohol_content', models.CharField(max_length=5)),
                ('temperature', models.CharField(max_length=5)),
                ('ingredients', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=beers.models.upload_image_path)),
            ],
        ),
    ]
