# Generated by Django 2.1.7 on 2019-02-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='harmonization',
        ),
    ]
