# Generated by Django 2.1.7 on 2019-02-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_remove_beer_harmonization'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='harmonization',
            field=models.CharField(choices=[('Aves', 'Aves'), ('Balada', 'Balada'), ('Bolinho de Bacalhau', 'Bolinho de Bacalhau'), ('Carne de Caça', 'Carne de Caça'), ('Chocolate', 'Chocolate'), ('Churrasco', 'Churrasco'), ('Costelinha de Porco', 'Costelinha de Porco'), ('Doces', 'Doces'), ('Frutos do Mar', 'Frutos do Mar'), ('Hambúrguer', 'Hambúrguer'), ('Massas', 'Massas'), ('Panna Costa', 'Panna Costa'), ('Petiscos de Boteco', 'Petiscos de Boteco'), ('Pizza', 'Pizza'), ('Queijos', 'Queijos'), ('Quitutes Apimentados', 'Quitutes Apimentados'), ('Saladas', 'Saladas')], default='Frutos do Mar', max_length=25),
            preserve_default=False,
        ),
    ]
