# Generated by Django 2.1.7 on 2019-02-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_beer_harmonization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='ingredients',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
