# Generated by Django 2.1.7 on 2019-02-21 21:20

import beers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20190221_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=beers.models.upload_image_path),
        ),
    ]
