# Generated by Django 2.1.7 on 2019-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20190221_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
